### ISSUE TITLE
would you mind finishing the shaggy port for me?

### ISSUE THREAD

**Issue by fnfporterhi** [Moxie-Stuff/ShitcanEngine-backup#1]
### What is your question?

i cant finish it cause i don't have time+next week is end of year tests

**Comment by moxie-coder** [comment]
I will when I have time and get around to it

**Comment by fnfporterhi** [comment]
ok thx

**Comment by moxie-coder** [comment]
yw

**Comment by moxie-coder** [comment]
also @fnfporterhi what needs to be finished??

**Comment by fnfporterhi** [comment]
i just saw this, basically the rest of assets

**Comment by moxie-coder** [comment]
alr
